### ISSUE TITLE
App cannot be installed/opened anymore

### ISSUE THREAD

**Issue by storres7** [ripeda/Privileges-Client#18]
After a few months of using the app, this week it simply stopped working. It is not possible to install it with the pkg available and when re-signed, it is possible to complete the installation, but the application does not open. No message is displayed under Privacy & Security > Security to open the app anyway.
Any ideas?
![image](https://github.com/ripeda/Privileges-Client/assets/62624843/767f31f8-c6f1-40fd-85c1-de8ae4bcf166)
![image](https://github.com/ripeda/Privileges-Client/assets/62624843/9307f1b4-db64-4c28-b8e1-37fa4ee3991f)

If resigned with another apple id installer certificate, the pkg can be installed, but the app cannot be opened.
<img width="372" alt="image" src="https://github.com/ripeda/Privileges-Client/assets/62624843/53b507c8-eb46-44ae-bdb6-acda087fc25a">

**Comment by khronokernel** [comment]
Hello,

The signing certificates were changed in October last year, and all support customers were transitioned over. And as a result, our legacy certificates were revoked last week.

* Reference: https://github.com/ripeda/Privileges-Client/commit/c2d780af1c6174ecc0b7c8fa6a9f35ffc2dd5c31

Unfortunately a new GitHub release was not created due to time constraints. We'll attempt to coordinate a release for the end of this month, however cannot guarantee this time frame for free open source projects when other projects take priority.

If you're an existing paid support customer or wish to be one, please reach out to `info@ripeda.com`. Otherwise we appreciate your patience.

**Comment by khronokernel** [comment]
https://github.com/ripeda/Privileges-Client/releases/tag/1.6.2
